USE [RiskTaker]
GO

/****** Object:  Table [dbo].[PRG_changecondition]    Script Date: 2026/04/20 8:49:43 ******/
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRG_changecondition](
	[RGcgc_ApprovalNo] [varchar](15) NOT NULL,
	[RGcgc_PrevApprovalNo] [varchar](15) NOT NULL,
	[RGcgc_ApprovalItemCode] [varchar](15) NOT NULL,
	[RGcgc_ExecScheduledDate] [char](8) NOT NULL,
	[RGcgc_RepaymentLimitDay] [char](8) NOT NULL,
	[RGcgc_CommodityCode] [varchar](8) NULL,
	[RGcgc_SecurityCode] [varchar](8) NULL,
	[RGcgc_ExecScheduledMoney] [money] NULL,
	[RGcgc_InterestRate] [decimal](8, 5) NULL,
	[RGcgc_InterestRateApplyDvsn] [varchar](15) NULL,
	[RGcgc_InterestSupplyRate] [decimal](8, 5) NULL,
	[RGcgc_VariableInterestCode] [varchar](15) NULL,
	[RGcgc_SlideRange] [decimal](8, 5) NULL,
	[RGcgc_StandardSpread] [decimal](8, 5) NULL,
	[RGcgc_RepaymentWayCode] [varchar](15) NULL,
	[RGcgc_RepayIntervalCode] [varchar](15) NULL,
	[RGcgc_RepaymentInterestCode] [varchar](15) NULL,
	[RGcgc_RepayInterestIntrvlCode] [varchar](15) NULL,
	[RGcgc_FirstRepayInterestDate] [char](8) NULL,
	[RGcgc_FirstRepayDate] [char](8) NULL,
	[RGcgc_BeforeExecMoney] [money] NULL,
	[RGcgc_BeforeInterestRate] [decimal](8, 5) NULL,
	[RGcgc_RootManagementNo] [int] NULL,
	[RGcgc_BonusTotalMoney] [money] NULL,
	[RGcgc_FixedContractualRate] [decimal](8, 5) NULL,
	[RGcgc_VariableContractualRate] [decimal](8, 5) NULL,
	[RGcgc_StepRateAppliedDate] [char](8) NULL,
	[RGcgc_StepRate] [decimal](8, 5) NULL,
	[RGcgc_StepPeriod] [char](2) NULL,
	[RGcgc_CapitalUseDetailDivision] [varchar](15) NULL,
	[RGcgc_RepayDay] [char](2) NULL,
	[RGcgc_FractionDivision] [varchar](15) NULL,
	[RGcgc_DeferInterestIntrvlCode] [varchar](15) NULL,
	[RGcgc_RepayCount1] [smallint] NULL,
	[RGcgc_EveryRepayMoney2] [money] NULL,
	[RGcgc_BonusRepayMoney] [money] NULL,
	[RGcgc_BonusRepayCount] [smallint] NULL,
	[RGcgc_BonusBeginDate] [char](6) NULL,
	[RGcgc_BonusMonth1] [char](2) NULL,
	[RGcgc_BonusMonth2] [char](2) NULL,
	[RGcgc_StartRepayDate1] [char](8) NULL,
	[RGcgc_RepayDay1] [char](2) NULL,
	[RGcgc_LastRepayDate1] [char](8) NULL,
	[RGcgc_RepayIntervalCode1] [varchar](15) NULL,
	[RGcgc_IncreaseDecreaseMoney1] [money] NULL,
	[RGcgc_StartRepayDate2] [char](8) NULL,
	[RGcgc_RepayDay2] [char](2) NULL,
	[RGcgc_LastRepayDate2] [char](8) NULL,
	[RGcgc_RepayIntervalCode2] [varchar](15) NULL,
	[RGcgc_IncreaseDecreaseMoney2] [money] NULL,
	[RGcgc_StartRepayDate3] [char](8) NULL,
	[RGcgc_RepayDay3] [char](2) NULL,
	[RGcgc_LastRepayDate3] [char](8) NULL,
	[RGcgc_RepayIntervalCode3] [varchar](15) NULL,
	[RGcgc_IncreaseDecreaseMoney3] [money] NULL,
	[RGcgc_StartRepayDate4] [char](8) NULL,
	[RGcgc_RepayDay4] [char](2) NULL,
	[RGcgc_LastRepayDate4] [char](8) NULL,
	[RGcgc_RepayIntervalCode4] [varchar](15) NULL,
	[RGcgc_IncreaseDecreaseMoney4] [money] NULL,
	[RGcgc_StartRepayDate5] [char](8) NULL,
	[RGcgc_RepayDay5] [char](2) NULL,
	[RGcgc_LastRepayDate5] [char](8) NULL,
	[RGcgc_RepayIntervalCode5] [varchar](15) NULL,
	[RGcgc_IncreaseDecreaseMoney5] [money] NULL,
	[RGcgc_EveryRepayMoney3] [money] NULL,
	[RGcgc_ApprovalTypeCode] [varchar](15) NULL,
	[RGcgc_CapitalUseDivision] [varchar](15) NULL,
	[RGcgc_JikkouDate] [char](8) NULL,
	[RGcgc_TanpoKubun] [varchar](8) NULL,
	[RGcgc_KyokudoFlg] [tinyint] NULL,
	[RGcgc_AccruedDelayInterest] [money] NULL,
	[RGcgc_BillLimitDate] [char](8) NULL,
	[RGcgc_InterestSettledDate] [char](8) NULL,
	[RGcgc_FixInerestTerm] [char](8) NULL,
	[RGcgc_InerestSelectDivision] [varchar](15) NULL,
	[RGcgc_ResponsibilityDivision] [varchar](15) NULL,
	[RGcgc_RepaymentDivision] [tinyint] NULL,
	[RGcgc_BNSOldRateInterest] [money] NULL,
	[RGcgc_BNSSumFlag] [char](1) NULL,
	[RGcgc_BNSAccruedTMoney] [money] NULL,
	[RGcgc_BNSAccruedIMoney] [money] NULL,
	[RGcgc_RegularProfitMargin] [decimal](8, 5) NULL,
	[RGcgc_DelayInterestMoney] [money] NULL,
	[RGcgc_DelayInterestCalcEndDate] [char](8) NULL,
	[RGcgc_ManagemntCreditFlag] [char](1) NULL,
	[RGcgc_TimeLimitExStopFlag] [char](1) NULL,
	[RGcgc_InterestApplyStartDiv] [char](2) NULL,
	[RGcgc_PrincipalCounterItem] [char](7) NULL,
	[RGcgc_InterestCounterItem] [char](7) NULL,
	[RGcgc_PrcpInterestCollDate] [char](8) NULL,
	[RGcgc_NowConditionStartDate] [char](8) NULL,
	[RGcgc_RegularInterestEndDate] [char](8) NULL,
	[RGcgc_AccountStartDate] [char](8) NULL,
	[RGcgc_FinalHolidayRevisedDiv] [char](1) NULL,
	[RGcgc_NextInterestSelectDiv] [char](2) NULL,
	[RGcgc_NextInterestMoney] [money] NULL,
	[RGcgc_NextRate] [decimal](8, 5) NULL,
	[RGcgc_NextRateApplyDate] [char](8) NULL,
	[RGcgc_ExecuteStopFlag] [char](1) NULL,
	[RGcgc_SyokaiRibaraiDate] [char](8) NULL,
	[RGcgc_ConsumerLoanFlag] [char](1) NULL,
	[RGcgc_ConditionChangeDate] [char](8) NULL,
	[RGcgc_ConditionChangeFlag] [char](1) NULL,
	[RGcgc_LastRepayInterestDate] [char](8) NULL,
	[RGcgc_LastRateEndDate] [char](8) NULL,
	[RGcgc_OverdraftInterestMoney] [money] NULL,
	[RGcgc_PaymentInSubrogationFlag] [char](1) NULL,
	[RGcgc_AdditionalInterestMoney] [money] NULL,
	[RGcgc_NotFixedFormSumMoney] [money] NULL,
	[RGcgc_InsideAmount] [money] NULL,
	[RGcgc_FloatingLowerRate] [decimal](8, 5) NULL,
	[RGcgc_AccruedDelayMoney] [money] NULL,
	[RGcgc_AccruedTMoney] [money] NULL,
	[RGcgc_AccruedIMoney] [money] NULL,
	[RGcgc_ReturnInterestMoney] [money] NULL,
	[RGcgc_TreatProfitMargin] [decimal](8, 5) NULL,
	[RGcgc_InterestCollectedEndDate] [char](8) NULL,
	[RGcgc_InterestCollectedDate] [char](8) NULL,
	[RGcgc_InterestCalcDate] [char](8) NULL,
	[RGcgc_LatestCalcMoveDate] [char](8) NULL,
	[RGcgc_Rollover] [varchar](15) NULL,
	[RGcgc_GroupInsuranceDivision] [varchar](15) NULL,
	[RGcgc_FloatingUpperRate] [decimal](8, 5) NULL,
	[RGcgc_InstallmentChangeDiv] [char](1) NULL,
	[RGcgc_InstallmentBaseYears] [smallint] NULL,
	[RGcgc_RegularInterestCount] [smallint] NULL,
	[RGcgc_NoFloatingBDivideFlag] [char](1) NULL,
	[RGcgc_SyokaiHensaiDate] [char](8) NULL,
	[RGcgc_LastLimitDate] [char](8) NULL,
	[RGcgc_FinalDivideExecuteDate] [char](8) NULL,
	[RGcgc_KyokudonaiZandaka] [money] NULL,
	[RGcgc_KyokudoZandaka] [money] NULL,
	[RGcgc_KijituTo] [char](8) NULL,
	[InsertDateTime] [datetime] NOT NULL,
	[InsertUserNo] [char](12) NOT NULL,
	[UpdateDateTime] [datetime] NOT NULL,
	[UpdateUserNo] [char](12) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RGcgc_ApprovalNo] ASC,
	[RGcgc_PrevApprovalNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRG_changecondition] ADD  DEFAULT (getdate()) FOR [InsertDateTime]
GO

ALTER TABLE [dbo].[PRG_changecondition] ADD  DEFAULT (getdate()) FOR [UpdateDateTime]
GO

