table_name: PJG_saikenmeisai
primary_key:
- JGskm_SyoriId
- JGskm_ShinseiNo
- JGskm_KasitukeNo
columns:
- name: JGskm_SyoriId
  type: char
  length: '16'
  nullable: false
- name: JGskm_BranchNo
  type: char
  length: '4'
  nullable: false
- name: JGskm_CustomerNo
  type: char
  length: '12'
  nullable: false
- name: JGskm_KijyunNengetu
  type: char
  length: '6'
  nullable: false
- name: JGskm_ShinseiNo
  type: bigint
  length: null
  nullable: false
- name: JGskm_KasitukeNo
  type: int
  length: null
  nullable: false
- name: JGskm_Kamoku
  type: varchar
  length: '15'
  nullable: false
- name: JGskm_Riritu
  type: decimal
  length: 8, 5
  nullable: true
- name: JGskm_ShinseiDate
  type: char
  length: '8'
  nullable: true
- name: JGskm_ShinseiKigen
  type: char
  length: '8'
  nullable: true
- name: JGskm_TousyoJikkouDate
  type: char
  length: '8'
  nullable: true
- name: JGskm_Kijitu
  type: char
  length: '8'
  nullable: true
- name: JGskm_SyoninKigen
  type: char
  length: '8'
  nullable: true
- name: JGskm_KasitukeZandaka
  type: money
  length: null
  nullable: true
- name: JGskm_TousyoJikkouKingaku
  type: money
  length: null
  nullable: true
- name: JGskm_SikinSito
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_HosyoMokuteki
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_HensaiHouhou
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_SyokaiHensaiDate
  type: char
  length: '8'
  nullable: true
- name: JGskm_SyokaiHensaigaku
  type: money
  length: null
  nullable: true
- name: JGskm_TotyukaiHensaigaku
  type: money
  length: null
  nullable: true
- name: JGskm_SaisyukaiHensaigaku
  type: money
  length: null
  nullable: true
- name: JGskm_HensaiSyuki
  type: smallint
  length: null
  nullable: true
- name: JGskm_EntaiGanpon
  type: money
  length: null
  nullable: true
- name: JGskm_EntaiKikan
  type: smallint
  length: null
  nullable: true
- name: JGskm_MondaiSaikenTokutei
  type: tinyint
  length: null
  nullable: true
- name: JGskm_JoukenHenkou
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_KjkKanwaSaiken
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_KengenKubun
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_HimotukiTanpo
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_HimotukiHosyo
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_Bikou
  type: varchar
  length: '256'
  nullable: true
- name: JGskm_Tokukasi1HendouKingaku
  type: money
  length: null
  nullable: true
- name: JGskm_Tokukasi1HendouJiyu
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_Tokukasi1HendouComment
  type: varchar
  length: '30'
  nullable: true
- name: JGskm_Tokukasi2HendouKingaku
  type: money
  length: null
  nullable: true
- name: JGskm_Tokukasi2HendouJiyu
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_Tokukasi2HendouComment
  type: varchar
  length: '30'
  nullable: true
- name: JGskm_Tokukasi3HendouKingaku
  type: money
  length: null
  nullable: true
- name: JGskm_Tokukasi3HendouJiyu
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_Tokukasi3HendouComment
  type: varchar
  length: '30'
  nullable: true
- name: JGskm_Tokukasi4HendouKingaku
  type: money
  length: null
  nullable: true
- name: JGskm_Tokukasi4HendouJiyu
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_Tokukasi4HendouComment
  type: varchar
  length: '30'
  nullable: true
- name: JGskm_Tokukasi1KoteiKingaku
  type: money
  length: null
  nullable: true
- name: JGskm_Tokukasi1KoteiJiyu
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_Tokukasi1KoteiComment
  type: varchar
  length: '30'
  nullable: true
- name: JGskm_Tokukasi2KoteiKingaku
  type: money
  length: null
  nullable: true
- name: JGskm_Tokukasi2KoteiJiyu
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_Tokukasi2KoteiComment
  type: varchar
  length: '30'
  nullable: true
- name: JGskm_Tokukasi3KoteiKingaku
  type: money
  length: null
  nullable: true
- name: JGskm_Tokukasi3KoteiJiyu
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_Tokukasi3KoteiComment
  type: varchar
  length: '30'
  nullable: true
- name: JGskm_Tokukasi4KoteiKingaku
  type: money
  length: null
  nullable: true
- name: JGskm_Tokukasi4KoteiJiyu
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_Tokukasi4KoteiComment
  type: varchar
  length: '30'
  nullable: true
- name: JGskm_Hosei
  type: tinyint
  length: null
  nullable: false
- name: JGskm_LoanFlg
  type: tinyint
  length: null
  nullable: false
- name: JGskm_SyohinCode
  type: varchar
  length: '8'
  nullable: true
- name: JGskm_TanpoCode
  type: varchar
  length: '6'
  nullable: true
- name: JGskm_RisokuDate
  type: char
  length: '8'
  nullable: true
- name: JGskm_KyokudoFlg
  type: tinyint
  length: null
  nullable: true
- name: JGskm_BISShikibetsu1
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_BISShikibetsu2
  type: varchar
  length: '15'
  nullable: true
- name: JGskm_SinkiTourokuDate
  type: datetime
  length: null
  nullable: false
- name: JGskm_SinkiTourokuUserNo
  type: char
  length: '10'
  nullable: false
- name: JGskm_LastUpdate
  type: datetime
  length: null
  nullable: true
- name: JGskm_UpdateUserNo
  type: char
  length: '10'
  nullable: true
required_fields:
- JGskm_SyoriId
- JGskm_BranchNo
- JGskm_CustomerNo
- JGskm_KijyunNengetu
- JGskm_ShinseiNo
- JGskm_KasitukeNo
- JGskm_Kamoku
- JGskm_Hosei
- JGskm_LoanFlg
- JGskm_SinkiTourokuDate
- JGskm_SinkiTourokuUserNo
primary_key_count: 3
