table_name: PRG_loanapproval
primary_key:
- RGlap_ApprovalNo
columns:
- name: RGlap_ApprovalNo
  type: varchar
  length: '15'
  nullable: false
- name: RGlap_CustomerId
  type: bigint
  length: null
  nullable: false
- name: RGlap_ApprovalTypeCode
  type: varchar
  length: '15'
  nullable: false
- name: RGlap_DealingTypeCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_ApprovalItemCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_LmtApprovalNo
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_LmtMoney
  type: money
  length: null
  nullable: true
- name: RGlap_LmtMrgMoney
  type: money
  length: null
  nullable: true
- name: RGlap_LmtMrgCalcBaseDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_LmtStartDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_LmtEndDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_LmtInterestRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_RequestReceiptNo
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_PrevApprovalNo
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_OriginalApprovalNo
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SettAuthorityCode
  type: varchar
  length: '15'
  nullable: false
- name: RGlap_ExecScheduledDate
  type: char
  length: '8'
  nullable: false
- name: RGlap_RepaymentLimitDay
  type: char
  length: '8'
  nullable: true
- name: RGlap_CommodityCode
  type: varchar
  length: '8'
  nullable: true
- name: RGlap_SecurityDivision
  type: varchar
  length: '8'
  nullable: true
- name: RGlap_ExecScheduledMoney
  type: money
  length: null
  nullable: true
- name: RGlap_InterestRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_InterestRateApplyType
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_InterestSupplyRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_VariableInterestCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SlideRange
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_StandardSpread
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_LoanTotal
  type: money
  length: null
  nullable: true
- name: RGlap_DepositTotal
  type: money
  length: null
  nullable: true
- name: RGlap_LoanInterestTotal
  type: money
  length: null
  nullable: true
- name: RGlap_DepositInterestTotal
  type: money
  length: null
  nullable: true
- name: RGlap_HeadBranchCalcRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_HeadBranchCalcDebitRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_HeadBranchCalcCreditRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_RelatedRealInterestRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_RelatedDpstFinanceRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_RelatedAnnualProfits
  type: money
  length: null
  nullable: true
- name: RGlap_CapitalUseDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_CapitalUseDetailDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_CapitalUseDetailDesc
  type: varchar
  length: '500'
  nullable: true
- name: RGlap_RaiseDetailItem1
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_RaiseDetailItem2
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_RaiseDetailItem3
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_RaiseDetailMoney1
  type: money
  length: null
  nullable: true
- name: RGlap_RaiseDetailMoney2
  type: money
  length: null
  nullable: true
- name: RGlap_RaiseDetailMoney3
  type: money
  length: null
  nullable: true
- name: RGlap_FundsOnHandMoney
  type: money
  length: null
  nullable: true
- name: RGlap_RepaymentWayCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_RepaymentInterestCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_FirstRepayInterestDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_FirstRepayDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayIntervalCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_RepayInterestIntrvlCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_RepayCapital
  type: varchar
  length: '500'
  nullable: true
- name: RGlap_RepayCount1
  type: smallint
  length: null
  nullable: true
- name: RGlap_RepayCount2
  type: smallint
  length: null
  nullable: true
- name: RGlap_RepayCount3
  type: smallint
  length: null
  nullable: true
- name: RGlap_EveryRepayMoney1
  type: money
  length: null
  nullable: true
- name: RGlap_EveryRepayMoney2
  type: money
  length: null
  nullable: true
- name: RGlap_EveryRepayMoney3
  type: money
  length: null
  nullable: true
- name: RGlap_SecurityFloatingExistFlg
  type: tinyint
  length: null
  nullable: true
- name: RGlap_SecurityDesc
  type: varchar
  length: '500'
  nullable: true
- name: RGlap_Remarks
  type: varchar
  length: '500'
  nullable: true
- name: RGlap_WideUseApprovalDtls
  type: varchar
  length: '500'
  nullable: true
- name: RGlap_SubTitle
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SubTitleSupplement
  type: varchar
  length: '40'
  nullable: true
- name: RGlap_ConditionCngTypeCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_ConditionExmptCrdtCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_ReleaseJdgmntIntrstRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_ApplyInterestRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_ConditionExemptDesc
  type: varchar
  length: '500'
  nullable: true
- name: RGlap_OldVersionFlag
  type: tinyint
  length: null
  nullable: false
- name: RGlap_RegisterFlag
  type: tinyint
  length: null
  nullable: false
- name: RGlap_RenovationFlag
  type: tinyint
  length: null
  nullable: false
- name: RGlap_DraftDate
  type: datetime
  length: null
  nullable: false
- name: RGlap_DraftUserName
  type: varchar
  length: '30'
  nullable: false
- name: RGlap_SecurityCode
  type: varchar
  length: '8'
  nullable: true
- name: RGlap_TempFlag
  type: tinyint
  length: null
  nullable: true
- name: RGlap_InChargeUserNo
  type: char
  length: '12'
  nullable: true
- name: RGlap_InChargeUserName
  type: varchar
  length: '30'
  nullable: true
- name: RGlap_HQInChargeUserNo
  type: char
  length: '12'
  nullable: true
- name: RGlap_HQInChargeUserName
  type: varchar
  length: '30'
  nullable: true
- name: RGlap_ChangeStandardDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_CreditNo
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_BillLimitDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_RootManagementNo
  type: int
  length: null
  nullable: true
- name: RGlap_SheetCount
  type: smallint
  length: null
  nullable: true
- name: RGlap_BonusTotalMoney
  type: money
  length: null
  nullable: true
- name: RGlap_ForeignMoney
  type: decimal
  length: 15, 2
  nullable: true
- name: RGlap_MonetaryUnit
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_Reservation
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_RefinanceDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_RefinanceFirstDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_RefinanceUseDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SelectTypeDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_FixedContractualRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_VariableContractualRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_StepRateAppliedDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_StepRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_StepPeriod
  type: char
  length: '2'
  nullable: true
- name: RGlap_OperateDetailItem1
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_OperateDetailItem2
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_OperateDetailItem3
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_OperateDetailItem4
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_OperateDetailItem5
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_OperateDetailItem6
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_OperateDetailItem7
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_OperateDetailItem8
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_OperateDetailItem9
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_OperateDetailMoney1
  type: money
  length: null
  nullable: true
- name: RGlap_OperateDetailMoney2
  type: money
  length: null
  nullable: true
- name: RGlap_OperateDetailMoney3
  type: money
  length: null
  nullable: true
- name: RGlap_OperateDetailMoney4
  type: money
  length: null
  nullable: true
- name: RGlap_OperateDetailMoney5
  type: money
  length: null
  nullable: true
- name: RGlap_OperateDetailMoney6
  type: money
  length: null
  nullable: true
- name: RGlap_OperateDetailMoney7
  type: money
  length: null
  nullable: true
- name: RGlap_OperateDetailMoney8
  type: money
  length: null
  nullable: true
- name: RGlap_OperateDetailMoney9
  type: money
  length: null
  nullable: true
- name: RGlap_RaiseDetailItem4
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_RaiseDetailItem5
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_RaiseDetailItem6
  type: varchar
  length: '12'
  nullable: true
- name: RGlap_RaiseDetailMoney4
  type: money
  length: null
  nullable: true
- name: RGlap_RaiseDetailMoney5
  type: money
  length: null
  nullable: true
- name: RGlap_RaiseDetailMoney6
  type: money
  length: null
  nullable: true
- name: RGlap_RepayDay
  type: char
  length: '2'
  nullable: true
- name: RGlap_FractionDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_DeferInterestIntrvlCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_BonusRepayMoney
  type: money
  length: null
  nullable: true
- name: RGlap_BonusRepayCount
  type: smallint
  length: null
  nullable: true
- name: RGlap_BonusBeginDate
  type: char
  length: '6'
  nullable: true
- name: RGlap_BonusMonth1
  type: char
  length: '2'
  nullable: true
- name: RGlap_BonusMonth2
  type: char
  length: '2'
  nullable: true
- name: RGlap_CommissionDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_GroupInsuranceDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_DebtSupport
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_FireInsuranceFlag
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_StartRepayDate1
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayDay1
  type: char
  length: '2'
  nullable: true
- name: RGlap_LastRepayDate1
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayIntervalCode1
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_IncreaseDecreaseMoney1
  type: money
  length: null
  nullable: true
- name: RGlap_StartRepayDate2
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayDay2
  type: char
  length: '2'
  nullable: true
- name: RGlap_LastRepayDate2
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayIntervalCode2
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_IncreaseDecreaseMoney2
  type: money
  length: null
  nullable: true
- name: RGlap_StartRepayDate3
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayDay3
  type: char
  length: '2'
  nullable: true
- name: RGlap_LastRepayDate3
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayIntervalCode3
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_IncreaseDecreaseMoney3
  type: money
  length: null
  nullable: true
- name: RGlap_StartRepayDate4
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayDay4
  type: char
  length: '2'
  nullable: true
- name: RGlap_LastRepayDate4
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayIntervalCode4
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_IncreaseDecreaseMoney4
  type: money
  length: null
  nullable: true
- name: RGlap_StartRepayDate5
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayDay5
  type: char
  length: '2'
  nullable: true
- name: RGlap_LastRepayDate5
  type: char
  length: '8'
  nullable: true
- name: RGlap_RepayIntervalCode5
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_IncreaseDecreaseMoney5
  type: money
  length: null
  nullable: true
- name: RGlap_RelatedLoanTotal
  type: money
  length: null
  nullable: true
- name: RGlap_RelatedDepositTotal
  type: money
  length: null
  nullable: true
- name: RGlap_RelatedLoanInterestTotal
  type: money
  length: null
  nullable: true
- name: RGlap_RelatedDpstInterestTotal
  type: money
  length: null
  nullable: true
- name: RGlap_DraftBranchNo
  type: char
  length: '4'
  nullable: true
- name: RGlap_DraftBranchName
  type: varchar
  length: '20'
  nullable: true
- name: RGlap_ExecutionBranchNo
  type: char
  length: '4'
  nullable: true
- name: RGlap_StaffFinanceFlag
  type: tinyint
  length: null
  nullable: true
- name: RGlap_ScheduledCloseMoney
  type: money
  length: null
  nullable: true
- name: RGlap_SimulScheduledCloseMoney
  type: money
  length: null
  nullable: true
- name: RGlap_DepositSecurityMny
  type: money
  length: null
  nullable: true
- name: RGlap_SimulDepositSecurityMny
  type: money
  length: null
  nullable: true
- name: RGlap_SocietyLoadMoney
  type: money
  length: null
  nullable: true
- name: RGlap_SimulSocietyLoadMoney
  type: money
  length: null
  nullable: true
- name: RGlap_AutoJudgeSettAuthority
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SettAuthorityJudgeDate
  type: datetime
  length: null
  nullable: true
- name: RGlap_SettAuthorityJudgeReason
  type: varchar
  length: '255'
  nullable: true
- name: RGlap_RespShareDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_ReceiptYear
  type: char
  length: '4'
  nullable: true
- name: RGlap_FixedIntstRateSelectDate
  type: char
  length: '8'
  nullable: true
- name: RGlap_AppSlipErrFlag
  type: tinyint
  length: null
  nullable: false
- name: RGlap_BasisCondUpdateTime
  type: datetime
  length: null
  nullable: false
- name: RGlap_AutoCalcEveryRepayMoney2
  type: money
  length: null
  nullable: true
- name: RGlap_AutoCalcBonusRepayMoney
  type: money
  length: null
  nullable: true
- name: RGlap_TempAdmitFlag
  type: tinyint
  length: null
  nullable: false
- name: RGlap_ChushinSecurityFlag
  type: tinyint
  length: null
  nullable: false
- name: RGlap_ReapplicationCode
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_EstablishmentSupport
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_BusinessAssessment
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_ReapplyPrevApprovalNo
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_BackinApproval
  type: tinyint
  length: null
  nullable: true
- name: RGlap_RateDownCreditNo
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_NowSelectTypeDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_NowInterestRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_SelectTypeDivision1
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SelectTypeRate1
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_SelectTypeDivision2
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SelectTypeRate2
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_SelectTypeDivision3
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SelectTypeRate3
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_SelectTypeDivision4
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SelectTypeRate4
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_SelectTypeDivision5
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SelectTypeRate5
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_SelectTypeDivision6
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SelectTypeRate6
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_SelectTypeDivision7
  type: varchar
  length: '15'
  nullable: true
- name: RGlap_SelectTypeRate7
  type: decimal
  length: 8, 5
  nullable: true
- name: RGlap_ConditionApprovalFlag
  type: tinyint
  length: null
  nullable: false
- name: InsertDateTime
  type: datetime
  length: null
  nullable: false
- name: InsertUserNo
  type: char
  length: '12'
  nullable: false
- name: UpdateDateTime
  type: datetime
  length: null
  nullable: false
- name: UpdateUserNo
  type: char
  length: '12'
  nullable: false
required_fields:
- RGlap_ApprovalNo
- RGlap_CustomerId
- RGlap_ApprovalTypeCode
- RGlap_SettAuthorityCode
- RGlap_ExecScheduledDate
- RGlap_OldVersionFlag
- RGlap_RegisterFlag
- RGlap_RenovationFlag
- RGlap_DraftDate
- RGlap_DraftUserName
- RGlap_AppSlipErrFlag
- RGlap_BasisCondUpdateTime
- RGlap_TempAdmitFlag
- RGlap_ChushinSecurityFlag
- RGlap_ConditionApprovalFlag
- InsertDateTime
- InsertUserNo
- UpdateDateTime
- UpdateUserNo
primary_key_count: 1
