table_name: PRG_changecondition
primary_key:
- RGcgc_ApprovalNo
- RGcgc_PrevApprovalNo
columns:
- name: RGcgc_ApprovalNo
  type: varchar
  length: '15'
  nullable: false
- name: RGcgc_PrevApprovalNo
  type: varchar
  length: '15'
  nullable: false
- name: RGcgc_ApprovalItemCode
  type: varchar
  length: '15'
  nullable: false
- name: RGcgc_ExecScheduledDate
  type: char
  length: '8'
  nullable: false
- name: RGcgc_RepaymentLimitDay
  type: char
  length: '8'
  nullable: false
- name: RGcgc_CommodityCode
  type: varchar
  length: '8'
  nullable: true
- name: RGcgc_SecurityCode
  type: varchar
  length: '8'
  nullable: true
- name: RGcgc_ExecScheduledMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_InterestRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_InterestRateApplyDvsn
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_InterestSupplyRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_VariableInterestCode
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_SlideRange
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_StandardSpread
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_RepaymentWayCode
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_RepayIntervalCode
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_RepaymentInterestCode
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_RepayInterestIntrvlCode
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_FirstRepayInterestDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_FirstRepayDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_BeforeExecMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_BeforeInterestRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_RootManagementNo
  type: int
  length: null
  nullable: true
- name: RGcgc_BonusTotalMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_FixedContractualRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_VariableContractualRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_StepRateAppliedDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_StepRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_StepPeriod
  type: char
  length: '2'
  nullable: true
- name: RGcgc_CapitalUseDetailDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_RepayDay
  type: char
  length: '2'
  nullable: true
- name: RGcgc_FractionDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_DeferInterestIntrvlCode
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_RepayCount1
  type: smallint
  length: null
  nullable: true
- name: RGcgc_EveryRepayMoney2
  type: money
  length: null
  nullable: true
- name: RGcgc_BonusRepayMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_BonusRepayCount
  type: smallint
  length: null
  nullable: true
- name: RGcgc_BonusBeginDate
  type: char
  length: '6'
  nullable: true
- name: RGcgc_BonusMonth1
  type: char
  length: '2'
  nullable: true
- name: RGcgc_BonusMonth2
  type: char
  length: '2'
  nullable: true
- name: RGcgc_StartRepayDate1
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayDay1
  type: char
  length: '2'
  nullable: true
- name: RGcgc_LastRepayDate1
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayIntervalCode1
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_IncreaseDecreaseMoney1
  type: money
  length: null
  nullable: true
- name: RGcgc_StartRepayDate2
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayDay2
  type: char
  length: '2'
  nullable: true
- name: RGcgc_LastRepayDate2
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayIntervalCode2
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_IncreaseDecreaseMoney2
  type: money
  length: null
  nullable: true
- name: RGcgc_StartRepayDate3
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayDay3
  type: char
  length: '2'
  nullable: true
- name: RGcgc_LastRepayDate3
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayIntervalCode3
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_IncreaseDecreaseMoney3
  type: money
  length: null
  nullable: true
- name: RGcgc_StartRepayDate4
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayDay4
  type: char
  length: '2'
  nullable: true
- name: RGcgc_LastRepayDate4
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayIntervalCode4
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_IncreaseDecreaseMoney4
  type: money
  length: null
  nullable: true
- name: RGcgc_StartRepayDate5
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayDay5
  type: char
  length: '2'
  nullable: true
- name: RGcgc_LastRepayDate5
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RepayIntervalCode5
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_IncreaseDecreaseMoney5
  type: money
  length: null
  nullable: true
- name: RGcgc_EveryRepayMoney3
  type: money
  length: null
  nullable: true
- name: RGcgc_ApprovalTypeCode
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_CapitalUseDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_JikkouDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_TanpoKubun
  type: varchar
  length: '8'
  nullable: true
- name: RGcgc_KyokudoFlg
  type: tinyint
  length: null
  nullable: true
- name: RGcgc_AccruedDelayInterest
  type: money
  length: null
  nullable: true
- name: RGcgc_BillLimitDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_InterestSettledDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_FixInerestTerm
  type: char
  length: '8'
  nullable: true
- name: RGcgc_InerestSelectDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_ResponsibilityDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_RepaymentDivision
  type: tinyint
  length: null
  nullable: true
- name: RGcgc_BNSOldRateInterest
  type: money
  length: null
  nullable: true
- name: RGcgc_BNSSumFlag
  type: char
  length: '1'
  nullable: true
- name: RGcgc_BNSAccruedTMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_BNSAccruedIMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_RegularProfitMargin
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_DelayInterestMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_DelayInterestCalcEndDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_ManagemntCreditFlag
  type: char
  length: '1'
  nullable: true
- name: RGcgc_TimeLimitExStopFlag
  type: char
  length: '1'
  nullable: true
- name: RGcgc_InterestApplyStartDiv
  type: char
  length: '2'
  nullable: true
- name: RGcgc_PrincipalCounterItem
  type: char
  length: '7'
  nullable: true
- name: RGcgc_InterestCounterItem
  type: char
  length: '7'
  nullable: true
- name: RGcgc_PrcpInterestCollDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_NowConditionStartDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_RegularInterestEndDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_AccountStartDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_FinalHolidayRevisedDiv
  type: char
  length: '1'
  nullable: true
- name: RGcgc_NextInterestSelectDiv
  type: char
  length: '2'
  nullable: true
- name: RGcgc_NextInterestMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_NextRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_NextRateApplyDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_ExecuteStopFlag
  type: char
  length: '1'
  nullable: true
- name: RGcgc_SyokaiRibaraiDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_ConsumerLoanFlag
  type: char
  length: '1'
  nullable: true
- name: RGcgc_ConditionChangeDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_ConditionChangeFlag
  type: char
  length: '1'
  nullable: true
- name: RGcgc_LastRepayInterestDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_LastRateEndDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_OverdraftInterestMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_PaymentInSubrogationFlag
  type: char
  length: '1'
  nullable: true
- name: RGcgc_AdditionalInterestMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_NotFixedFormSumMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_InsideAmount
  type: money
  length: null
  nullable: true
- name: RGcgc_FloatingLowerRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_AccruedDelayMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_AccruedTMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_AccruedIMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_ReturnInterestMoney
  type: money
  length: null
  nullable: true
- name: RGcgc_TreatProfitMargin
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_InterestCollectedEndDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_InterestCollectedDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_InterestCalcDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_LatestCalcMoveDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_Rollover
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_GroupInsuranceDivision
  type: varchar
  length: '15'
  nullable: true
- name: RGcgc_FloatingUpperRate
  type: decimal
  length: 8, 5
  nullable: true
- name: RGcgc_InstallmentChangeDiv
  type: char
  length: '1'
  nullable: true
- name: RGcgc_InstallmentBaseYears
  type: smallint
  length: null
  nullable: true
- name: RGcgc_RegularInterestCount
  type: smallint
  length: null
  nullable: true
- name: RGcgc_NoFloatingBDivideFlag
  type: char
  length: '1'
  nullable: true
- name: RGcgc_SyokaiHensaiDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_LastLimitDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_FinalDivideExecuteDate
  type: char
  length: '8'
  nullable: true
- name: RGcgc_KyokudonaiZandaka
  type: money
  length: null
  nullable: true
- name: RGcgc_KyokudoZandaka
  type: money
  length: null
  nullable: true
- name: RGcgc_KijituTo
  type: char
  length: '8'
  nullable: true
- name: InsertDateTime
  type: datetime
  length: null
  nullable: false
- name: InsertUserNo
  type: char
  length: '12'
  nullable: false
- name: UpdateDateTime
  type: datetime
  length: null
  nullable: false
- name: UpdateUserNo
  type: char
  length: '12'
  nullable: false
required_fields:
- RGcgc_ApprovalNo
- RGcgc_PrevApprovalNo
- RGcgc_ApprovalItemCode
- RGcgc_ExecScheduledDate
- RGcgc_RepaymentLimitDay
- InsertDateTime
- InsertUserNo
- UpdateDateTime
- UpdateUserNo
primary_key_count: 2
